import Link from "next/link"

import { SiteFooter } from "@/components/marketing/site-footer"
import { SiteHeader } from "@/components/marketing/site-header"

export const metadata = {
  title: "Terms & Conditions | EbooksHub",
  description: "The terms that govern your use of EbooksHub.",
}

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="flex-1 bg-paper py-16 sm:py-24">
        <article className="container max-w-3xl">
          <p className="text-sm font-medium text-gold">Legal</p>
          <h1 className="mt-2 font-display text-4xl font-medium tracking-tight text-foreground sm:text-5xl">Terms & Conditions</h1>
          <p className="mt-3 text-sm text-muted-foreground">
            Last updated {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </p>

          <div className="mt-10 space-y-10">
            <section>
              <h2 className="font-display text-xl font-medium text-foreground">Using EbooksHub</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                EbooksHub is a tool for planning, writing, illustrating, and exporting books with AI assistance. You
                must be at least 18 years old, or the age of majority in your jurisdiction, to create an account.
                You&apos;re responsible for the content you generate, edit, and publish through the service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-medium text-foreground">Your content</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                You own the books, text, and artwork you create using EbooksHub. You&apos;re responsible for
                ensuring your prompts and published content don&apos;t infringe on anyone else&apos;s rights or
                violate applicable law. We may remove content or suspend accounts that violate these terms.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-medium text-foreground">AI-generated content</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                Text and artwork are generated by third-party AI providers based on your prompts. AI output can be
                inaccurate or unpredictable — review and edit generated content before relying on or publishing it.
                We don&apos;t guarantee the accuracy, originality, or fitness for any particular purpose of
                AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-medium text-foreground">Subscriptions and billing</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                Paid plans are billed on a recurring basis through Stripe. See our{" "}
                <Link href="/refund" className="text-gold underline underline-offset-2 hover:text-gold/80">refund policy</Link>{" "}
                for cancellation and refund terms. You can cancel or delete your account at any time from Settings.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-medium text-foreground">Acceptable use</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                Don&apos;t use EbooksHub to generate illegal content, content that infringes on others&apos;
                intellectual property, or content intended to harass, defraud, or harm others. We may suspend or
                terminate accounts that violate this.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-medium text-foreground">Service availability</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                EbooksHub is provided &quot;as is.&quot; We aim for reliable uptime but don&apos;t guarantee the
                service will be uninterrupted or error-free, including generation quality, which depends on
                third-party AI providers outside our control.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-medium text-foreground">Changes to these terms</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                We may update these terms from time to time. Continued use of EbooksHub after changes take effect
                means you accept the updated terms.
              </p>
            </section>

            <section>
              <h2 className="font-display text-xl font-medium text-foreground">Contact</h2>
              <p className="mt-3 leading-relaxed text-foreground/90">
                Questions about these terms can be sent through our{" "}
                <Link href="/support" className="text-gold underline underline-offset-2 hover:text-gold/80">support page</Link>.
              </p>
            </section>
          </div>
        </article>
      </main>
      <SiteFooter />
    </div>
  )
}
